// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EmailRouterSendEmailWithTemplateRequest struct {
	// The Email Message
	RequestBody []byte `request:"mediaType=*/*"`
	// Sub-Account API Key
	XSubAccountAPIKey string `header:"style=simple,explode=false,name=X-SubAccount-ApiKey"`
}

type EmailRouterSendEmailWithTemplateResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
