// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type EmailRouterSendEmailRequest struct {
	// The Email Message
	RequestBody []byte `request:"mediaType=*/*"`
	// Mock email header
	XSendPostMockEmail *bool `header:"style=simple,explode=false,name=X-SendPost-Mock-Email"`
	// Mock email time shift
	XSendPostMockTimeShift *string `header:"style=simple,explode=false,name=X-SendPost-Mock-Time-Shift"`
	// Sub-Account API Key
	XSubAccountAPIKey string `header:"style=simple,explode=false,name=X-SubAccount-ApiKey"`
}

type EmailRouterSendEmailResponse struct {
	Body        []byte
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
