// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsToCustomFields struct {
}

type ModelsTo struct {
	Bcc          []ModelsCopyTo
	Cc           []ModelsCopyTo
	CustomFields *ModelsToCustomFields
	Email        *string
	Name         *string
}
