// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsEmailMessageGroups struct {
}

type ModelsEmailMessageHeaders struct {
}

type ModelsEmailMessage struct {
	AmpBody     *string
	Attachments []ModelsAttachment
	From        *ModelsFrom
	Groups      *ModelsEmailMessageGroups
	Headers     *ModelsEmailMessageHeaders
	HTMLBody    *string
	Ippool      *string
	PreText     *string
	ReplyTo     *ModelsReplyTo
	Subject     *string
	Template    *string
	TextBody    *string
	To          []ModelsTo
	TrackClicks *bool
	TrackOpens  *bool
}
