// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsEmailResponse struct {
	ErrorCode   *ModelsEmailErrorCode
	Message     *string
	MessageID   *string
	SubmittedAt *int64
	To          *string
}
