// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsEmailResponse struct {
	ErrorCode   *ModelsEmailErrorCode
	Message     *string
	MessageID   *string
	SubmittedAt *int64
	To          *string
}

func (o *ModelsEmailResponse) GetErrorCode() *ModelsEmailErrorCode {
	if o == nil {
		return nil
	}
	return o.ErrorCode
}

func (o *ModelsEmailResponse) GetMessage() *string {
	if o == nil {
		return nil
	}
	return o.Message
}

func (o *ModelsEmailResponse) GetMessageID() *string {
	if o == nil {
		return nil
	}
	return o.MessageID
}

func (o *ModelsEmailResponse) GetSubmittedAt() *int64 {
	if o == nil {
		return nil
	}
	return o.SubmittedAt
}

func (o *ModelsEmailResponse) GetTo() *string {
	if o == nil {
		return nil
	}
	return o.To
}
