// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsCopyToCustomFields struct {
}

type ModelsCopyTo struct {
	CustomFields *ModelsCopyToCustomFields
	Email        *string
	Name         *string
}
