// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsToCustomFields struct {
}

type ModelsTo struct {
	Bcc          []ModelsCopyTo
	Cc           []ModelsCopyTo
	CustomFields *ModelsToCustomFields
	Email        *string
	Name         *string
}

func (o *ModelsTo) GetBcc() []ModelsCopyTo {
	if o == nil {
		return nil
	}
	return o.Bcc
}

func (o *ModelsTo) GetCc() []ModelsCopyTo {
	if o == nil {
		return nil
	}
	return o.Cc
}

func (o *ModelsTo) GetCustomFields() *ModelsToCustomFields {
	if o == nil {
		return nil
	}
	return o.CustomFields
}

func (o *ModelsTo) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *ModelsTo) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
