// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ModelsAttachment struct {
	Content  *string
	Filename *string
}

func (o *ModelsAttachment) GetContent() *string {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *ModelsAttachment) GetFilename() *string {
	if o == nil {
		return nil
	}
	return o.Filename
}
